# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/rolla/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-18128-PORT-FIX/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
set_msg_config  -id {Project 1-19}  -string {{CRITICAL WARNING: [Project 1-19] Could not find the file 'C:/Users/jeanp/Documents/Ecole/ELE749/RV32EM-VHDL/RV32EM-VHDL.srcs/sources_1/new/Branch_Cmp.vhd'.}}  -suppress 
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/rolla/OneDrive/Documents/GitHub/RV32EM-VHDL/RV32EM-VHDL.cache/wt [current_project]
set_property parent.project_path C:/Users/rolla/OneDrive/Documents/GitHub/RV32EM-VHDL/RV32EM-VHDL.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/rolla/OneDrive/Documents/GitHub/RV32EM-VHDL/RV32EM-VHDL.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/rolla/OneDrive/Documents/GitHub/RV32EM-VHDL/RV32EM-VHDL.srcs/sources_1/new/ALU.vhd
  C:/Users/rolla/OneDrive/Documents/GitHub/RV32EM-VHDL/RV32EM-VHDL.srcs/sources_1/new/Branch_Compare.vhd
  C:/Users/rolla/OneDrive/Documents/GitHub/RV32EM-VHDL/RV32EM-VHDL.srcs/sources_1/new/Hazard_detection_unit.vhd
  C:/Users/rolla/OneDrive/Documents/GitHub/RV32EM-VHDL/RV32EM-VHDL.srcs/sources_1/new/Instruction_Memory.vhd
  C:/Users/rolla/OneDrive/Documents/GitHub/RV32EM-VHDL/RV32EM-VHDL.srcs/sources_1/new/Register_Memory.vhd
  C:/Users/rolla/OneDrive/Documents/GitHub/RV32EM-VHDL/RV32EM-VHDL.srcs/sources_1/new/control_unit.vhd
  C:/Users/rolla/OneDrive/Documents/GitHub/RV32EM-VHDL/RV32EM-VHDL.srcs/sources_1/new/data_memory.vhd
  C:/Users/rolla/OneDrive/Documents/GitHub/RV32EM-VHDL/RV32EM-VHDL.srcs/sources_1/new/part.vhd
  C:/Users/rolla/OneDrive/Documents/GitHub/RV32EM-VHDL/RV32EM-VHDL.srcs/sources_1/new/execute.vhd
  C:/Users/rolla/OneDrive/Documents/GitHub/RV32EM-VHDL/RV32EM-VHDL.srcs/sources_1/new/imm_gen.vhd
  C:/Users/rolla/OneDrive/Documents/GitHub/RV32EM-VHDL/RV32EM-VHDL.srcs/sources_1/new/instruction_decode.vhd
  C:/Users/rolla/OneDrive/Documents/GitHub/RV32EM-VHDL/RV32EM-VHDL.srcs/sources_1/new/instruction_fetch.vhd
  C:/Users/rolla/OneDrive/Documents/GitHub/RV32EM-VHDL/RV32EM-VHDL.srcs/sources_1/new/memory_access.vhd
  C:/Users/rolla/OneDrive/Documents/GitHub/RV32EM-VHDL/RV32EM-VHDL.srcs/sources_1/new/write_back.vhd
  C:/Users/rolla/OneDrive/Documents/GitHub/RV32EM-VHDL/RV32EM-VHDL.srcs/sources_1/new/top.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/rolla/OneDrive/Documents/GitHub/RV32EM-VHDL/RV32EM-VHDL.srcs/constrs_1/new/constraints_1.xdc
set_property used_in_implementation false [get_files C:/Users/rolla/OneDrive/Documents/GitHub/RV32EM-VHDL/RV32EM-VHDL.srcs/constrs_1/new/constraints_1.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Main -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Main.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Main_utilization_synth.rpt -pb Main_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
