# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/jeanp/Documents/Ecole/ELE749/RV32EM-VHDL/RV32EM-VHDL.srcs/sources_1/ip/Instruction_Memory/Instruction_Memory.xci
# IP: The module: 'Instruction_Memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jeanp/Documents/Ecole/ELE749/RV32EM-VHDL/RV32EM-VHDL.srcs/sources_1/ip/Instruction_Memory/Instruction_Memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Instruction_Memory'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/jeanp/Documents/Ecole/ELE749/RV32EM-VHDL/RV32EM-VHDL.srcs/sources_1/ip/Instruction_Memory/Instruction_Memory.xci
# IP: The module: 'Instruction_Memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jeanp/Documents/Ecole/ELE749/RV32EM-VHDL/RV32EM-VHDL.srcs/sources_1/ip/Instruction_Memory/Instruction_Memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Instruction_Memory'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
